name: MovieGen

dependencies:
- numpy
- pandas
- scipy
- scikit-learn
- pip:
  - flask
  - flask-qrcode
  - Flask-Session
  - redis
  - Flask-SocketIO
  - zmq
  - opendatasets
  - python-dotenv
  - flask_monitoringdashboard

